#!/bin/sh

##
# profile-check
#
# Check-up your profile's dotfiles.
#
# Copyright (c) 2020 Francesco Bianco <bianco@javanile.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
##

set -e

profile="$HOME/.profile"
dotfiles=".profile .bashrc .zshrc"
rcfile="$HOME/.$(basename $SHELL)rc"

echo "Looking for dot files."
echo "$dotfiles" | tr ' ' '\n' | while read file; do
  [ -f "$file" ] || continue
  [ -n "$(tail -c1 "$file")" ] && echo >> "$file"
  file="$PWD/$file"
  load_check="$file.profile-check"
  echo rm -f \"$load_check\" >> "$file"
  touch "$load_check"
done

echo "Default shell: $SHELL"
echo "Launch a shell under control to capture data..."
echo "====| Type 'exit' and press [enter] to continue |===="
(sleep 1; pkill -15 -f '/tmp/shell-profile-check')&
echo "$SHELL" > /tmp/shell-profile-check
$SHELL /tmp/shell-profile-check 2> /dev/null && sleep 1
rm -f /tmp/shell-profile-check
echo "====================================================="
echo "The shell under control was stopped."

echo ""
echo "Run files analysis:"
if [ ! -f "$rcfile" ]; then
  echo "[WARN] The file '$rcfile' is missing. "
  echo "       Consider to create it as default shell profile file."
fi
if [ ! -f "$profile" ]; then
  echo "[WARN] The file '$profile' is missing."
  echo "       Consider to create it as agnostic shell profile file."
fi
if [ "$PWD" != "$HOME" ]; then
  echo "[WARN] Your current directory is '$PWD/'."
  echo "       Consider to switch on '$HOME/' to have a more useful analysis."
fi
echo "$dotfiles" | tr ' ' '\n' | while read file; do
  [ -f "$file" ] || continue
  [ -n "$(tail -c1 "$file")" ] && echo >> "$file"
  file="$PWD/$file"
  load_check="$file.profile-check"
  mv "$file" "$file.profile-check.bak"
  sed '/^rm .*profile-check"$/d' "$file.profile-check.bak" > "$file"
  rm "$file.profile-check.bak"
  if [ -f "$load_check" ]; then
    echo "[WARN] The file '$file' is NOT loaded by default."
    echo "       Consider to add 'source $file' at end of '$rcfile' file."
  else
    echo "[INFO] The file '$file' is correctly loaded by your shell."
  fi
done
